version: '3.1'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-11}
  mail:
    image: mailhog/mailhog
  integration:
    image: my-registry:55000/gen:integration-10
    build: .